### ISSUE TITLE
Xcode 7.1 errors (not public methods)

### ISSUE THREAD

**Issue by melnikovpa** [zoonooz/ZFRippleButton#19]
Hello! 

Thank you for fix previews issue. But the code still have errors. You have some methods as private, this methods should be public.

http://joxi.ru/8ZrJodMieDlvmj

                cell.controlButton.rippleBackgroundColor = .grayColor()
                cell.controlButton.rippleColor = .lightGrayColor()
                cell.controlButton.ripplePercent = 1

Can you fix it?

**Comment by zoonooz** [comment]
:sweat_smile:
