### ISSUE TITLE
UIViewReportBrokenSuperviewChain iOS 10 crash

### ISSUE THREAD

**Issue by elprl** [zoonooz/ZFRippleButton#23]
I'm getting the following error on iOS 10. This is a new error so not seen a lot on Stackoverflow about this:
http://stackoverflow.com/questions/39565424/swift-uiviewreportbrokensuperviewchain-cause-by-layer-manipulation

` Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'View has lost track of its superview, most likely through unsupported use of CALayer API on the view's layer. If this isn't a crash yet, it will be in the near future. 
	Problem view: <UIView: 0x7e70e630; frame = (0 0; 72 205); alpha = 0; layer = <CALayer: 0x7a6521b0>>
	Expected parent: <ZFRippleButton.ZFRippleButton: 0x7a906fb0; baseClass = UIButton; frame = (528 12; 72 205); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x7e7144e0>>
Break on UIViewReportBrokenSuperviewChain to debug.'`

**Comment by elprl** [comment]
When I comment out
`layer.addSublayer(rippleBackgroundView.layer)`
I get no errors. 

All my buttons are added via Interface Builder, so no code.

**Comment by sravanco** [comment]
@elprl  But did the ripple effect exists after removing rippleBackgroundView?
I see no more ripple effect after commenting out this statement.

**Comment by sravanco** [comment]
Instead of layer, using view.addSubView(subView) did fix the problem.
```
rippleBackgroundView.addSubview(rippleView)
self.addSubview(rippleBackgroundView)
```

**Comment by elprl** [comment]
Yep, the ripple did stop after commenting out that line. It was just to highlight where the error was occurring. Good to know you fixed it.

**Comment by kiwo12345** [comment]
@elprl @sravanco What branch are you using? I could not find any swift 3 branch

**Comment by sravanco** [comment]
@kiwo12345 Neither I. Its just one file so I quickly adapted to Swift3. No Carthage support so I have to drop the file into my project. 
I didn't use but did you check this already,
https://github.com/zoonooz/ZFRippleButton/pull/21/commits/84df0f39c6d7eb78fcb501b3d074a2fcac30c218

**Comment by kiwo12345** [comment]
@sravanco Thanks!

**Comment by vitobellini** [comment]
I'm addressing a similar issue. My buttons are added on the view using Interface Builder, no code.
They were working fine on Xcode 7 / iOS 9. No changes are made with Xcode 8 / iOS 10, I just opened the project, run it on a real device and get this crash.

```
2016-10-21 10:02:48.620067 Cinemappy[9732:2494425] *** Assertion failure in void UIViewReportBrokenSuperviewChain(UIView *__strong, UIView *__strong, BOOL)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3599.6.1/UIView.m:190
2016-10-21 10:03:05.951306 Cinemappy[9732:2494425] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'View has lost track of its superview, most likely through unsupported use of CALayer API on the view's layer. If this isn't a crash yet, it will be in the near future. 
	Problem view: <UIView: 0x15fc91740; frame = (0 0; 1000 1000); alpha = 0; layer = <CALayer: 0x1746298c0>>
	Expected parent: <ZFRippleButton.ZFRippleButton: 0x15fc90b40; baseClass = UIButton; frame = (0 0; 1000 1000); opaque = NO; autoresize = RM+BM; tintColor = UIExtendedSRGBColorSpace 1 1 1 1; layer = <CALayer: 0x174821f20>>
Break on UIViewReportBrokenSuperviewChain to debug.'
*** First throw call stack:
(0x1894dc1c0 0x187f1455c 0x1894dc094 0x189f66898 0x18f604f9c 0x18f605658 0x18fc7b390 0x189f122bc 0x189f07ab8 0x189f0765c 0x189f07444 0x18f42a76c 0x18f42a4d0 0x18f371be0 0x19553fd04 0x19553fad4 0x195553d5c 0x18f6195e8 0x18f33beac 0x1893c91a4 0x1893c90a0 0x18f32ac30 0x18f427330 0x18f61f2c4 0x18f32254c 0x18c7ea40c 0x18c7df0e8 0x18c7defa8 0x18c75bc64 0x18c
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by kiwo12345** [comment]
@sravanco @elprl 
I dont think you have to add 

```
rippleBackgroundView.addSubview(rippleView)
self.addSubview(rippleBackgroundView) 
```

If you build the project in Xocde 8.1. Atleast i dont see the problem if I build in 8.1 and test on a device running ios >= 10

**Comment by vitobellini** [comment]
I was with Xcode 8.0, those two lines of code did the trick.
I'll check further with Xcode 8.1

## Ing. Vito Bellini

Mobile: (+39) 348 8908593
v.bellini@gmail.com
http://www.vitobellini.com
